"""Golden ALU test vectors generated by Python reference model.

Each vector: (src1, src2, alu_op, expected_result, expected_zero)
All values are unsigned integers in the given data width.
"""
from __future__ import annotations

OP_ADD = 0b0000
OP_SUB = 0b0001
OP_AND = 0b0010
OP_OR  = 0b0011
OP_XOR = 0b0100
OP_SLT = 0b1000
OP_SLTU = 0b1001
OP_SLL = 0b1010
OP_SRL = 0b1011
OP_SRA = 0b1100


def _signed(v: int, w: int) -> int:
    return v if v < (1 << (w - 1)) else v - (1 << w)


def gen_alu_vectors(width: int = 16) -> list[tuple[int, int, int, int, int]]:
    """Generate comprehensive ALU test vectors for given data width."""
    MASK = (1 << width) - 1
    MAX_SIGNED = (1 << (width - 1)) - 1
    MIN_SIGNED = 1 << (width - 1)
    SHAMT_W = max(1, (width - 1).bit_length())
    SHAMT_MASK = (1 << SHAMT_W) - 1

    def _alu(s1: int, s2: int, op: int) -> tuple[int, int]:
        s1, s2 = s1 & MASK, s2 & MASK
        if op == OP_ADD:
            r = (s1 + s2) & MASK
        elif op == OP_SUB:
            r = (s1 - s2) & MASK
        elif op == OP_AND:
            r = s1 & s2
        elif op == OP_OR:
            r = s1 | s2
        elif op == OP_XOR:
            r = s1 ^ s2
        elif op == OP_SLT:
            r = 1 if _signed(s1, width) < _signed(s2, width) else 0
        elif op == OP_SLTU:
            r = 1 if s1 < s2 else 0
        elif op == OP_SLL:
            r = (s1 << (s2 & SHAMT_MASK)) & MASK
        elif op == OP_SRL:
            r = (s1 >> (s2 & SHAMT_MASK)) & MASK
        elif op == OP_SRA:
            sv = _signed(s1, width)
            r = (sv >> (s2 & SHAMT_MASK)) & MASK
        else:
            r = 0
        return r, int(r == 0)

    vectors = []
    test_vals = [0, 1, 2, MAX_SIGNED, MIN_SIGNED, MASK, MASK - 1]
    ops = [OP_ADD, OP_SUB, OP_AND, OP_OR, OP_XOR, OP_SLT, OP_SLTU,
           OP_SLL, OP_SRL, OP_SRA]

    for op in ops:
        for s1 in test_vals:
            for s2 in test_vals[:5]:
                r, z = _alu(s1, s2, op)
                vectors.append((s1 & MASK, s2 & MASK, op, r, z))

    return vectors


ALU_VECTORS_16BIT = gen_alu_vectors(16)
ALU_VECTORS_64BIT = gen_alu_vectors(64)
