`include "pyc_reg.v"
`include "pyc_fifo.v"

`include "pyc_byte_mem.v"

`include "pyc_sync_mem.v"
`include "pyc_sync_mem_dp.v"
`include "pyc_async_fifo.v"
`include "pyc_cdc_sync.v"

// Generated by pycc (pyCircuit)
// Module: csu

module csu (
  input clk,
  input rst,
  input [41:0] rxrsp,
  input [583:0] rxdat,
  input [81:0] rxsnp,
  input [3:0] rsp1_side,
  input [17:0] rxwkup,
  input [1:0] rxerr,
  input [2:0] rxfill,
  input [96:0] tb_txreq_seed,
  input tb_issue_req,
  input [63:0] cfg_word,
  output [96:0] txreq,
  output [29:0] txrsp,
  output [614:0] txdat,
  output [1:0] txreq_pend
);

wire _v5_bal_1; // pyc.name="_v5_bal_1"
wire _v5_bal_1__next; // pyc.name="_v5_bal_1__next"
wire [96:0] _v5_bal_2; // pyc.name="_v5_bal_2"
wire [96:0] _v5_bal_2__next; // pyc.name="_v5_bal_2__next"
wire [3:0] f042_brq_stub; // pyc.name="f042_brq_stub"
wire [3:0] f042_brq_stub__next; // pyc.name="f042_brq_stub__next"
wire [15:0] f047_pmu_stub; // pyc.name="f047_pmu_stub"
wire [15:0] f047_pmu_stub__next; // pyc.name="f047_pmu_stub__next"
wire [15:0] f060_lfsr_stub; // pyc.name="f060_lfsr_stub"
wire [15:0] f060_lfsr_stub__next; // pyc.name="f060_lfsr_stub__next"
wire [7:0] f061_rrip_stub; // pyc.name="f061_rrip_stub"
wire [7:0] f061_rrip_stub__next; // pyc.name="f061_rrip_stub__next"
wire [127:0] feat_shaft_stub; // pyc.name="feat_shaft_stub"
wire [127:0] feat_shaft_stub__next; // pyc.name="feat_shaft_stub__next"
wire [96:0] latched_txreq; // pyc.name="latched_txreq"
wire [96:0] latched_txreq__next; // pyc.name="latched_txreq__next"
wire [63:0] mega_feature_0; // pyc.name="mega_feature_0"
wire [63:0] mega_feature_0__next; // pyc.name="mega_feature_0__next"
wire [63:0] mega_feature_1; // pyc.name="mega_feature_1"
wire [63:0] mega_feature_1__next; // pyc.name="mega_feature_1__next"
wire [63:0] mega_feature_2; // pyc.name="mega_feature_2"
wire [63:0] mega_feature_2__next; // pyc.name="mega_feature_2__next"
wire [63:0] mega_feature_3; // pyc.name="mega_feature_3"
wire [63:0] mega_feature_3__next; // pyc.name="mega_feature_3__next"
wire [63:0] mega_feature_4; // pyc.name="mega_feature_4"
wire [63:0] mega_feature_4__next; // pyc.name="mega_feature_4__next"
wire [63:0] mega_feature_5; // pyc.name="mega_feature_5"
wire [63:0] mega_feature_5__next; // pyc.name="mega_feature_5__next"
wire [63:0] mega_feature_6; // pyc.name="mega_feature_6"
wire [63:0] mega_feature_6__next; // pyc.name="mega_feature_6__next"
wire [63:0] mega_feature_7; // pyc.name="mega_feature_7"
wire [63:0] mega_feature_7__next; // pyc.name="mega_feature_7__next"
wire [1:0] pyc_add_179; // op=pyc.add
wire [3:0] pyc_add_282; // op=pyc.add
wire [15:0] pyc_add_286; // op=pyc.add
wire [7:0] pyc_add_290; // op=pyc.add
wire pyc_and_177; // op=pyc.and
wire pyc_and_178; // op=pyc.and
wire [6:0] pyc_comb_100; // op=pyc.comb
wire [6:0] pyc_comb_101; // op=pyc.comb
wire pyc_comb_102; // op=pyc.comb
wire pyc_comb_103; // op=pyc.comb
wire [2:0] pyc_comb_104; // op=pyc.comb
wire [17:0] pyc_comb_105; // op=pyc.comb
wire [1:0] pyc_comb_106; // op=pyc.comb
wire [96:0] pyc_comb_107; // op=pyc.comb
wire [31:0] pyc_comb_108; // op=pyc.comb
wire [96:0] pyc_comb_109; // op=pyc.comb
wire pyc_comb_110; // op=pyc.comb
wire pyc_comb_111; // op=pyc.comb
wire pyc_comb_112; // op=pyc.comb
wire [31:0] pyc_comb_113; // op=pyc.comb
wire [31:0] pyc_comb_114; // op=pyc.comb
wire [96:0] pyc_comb_121; // op=pyc.comb
wire pyc_comb_174; // op=pyc.comb
wire [96:0] pyc_comb_175; // op=pyc.comb
wire [1:0] pyc_comb_182; // op=pyc.comb
wire [1:0] pyc_comb_183; // op=pyc.comb
wire pyc_comb_184; // op=pyc.comb
wire [1:0] pyc_comb_185; // op=pyc.comb
wire [7:0] pyc_comb_226; // op=pyc.comb
wire [31:0] pyc_comb_227; // op=pyc.comb
wire [63:0] pyc_comb_228; // op=pyc.comb
wire [3:0] pyc_comb_229; // op=pyc.comb
wire [3:0] pyc_comb_230; // op=pyc.comb
wire [63:0] pyc_comb_237; // op=pyc.comb
wire [63:0] pyc_comb_238; // op=pyc.comb
wire [63:0] pyc_comb_243; // op=pyc.comb
wire [63:0] pyc_comb_248; // op=pyc.comb
wire [63:0] pyc_comb_253; // op=pyc.comb
wire [63:0] pyc_comb_258; // op=pyc.comb
wire [63:0] pyc_comb_263; // op=pyc.comb
wire [63:0] pyc_comb_268; // op=pyc.comb
wire [63:0] pyc_comb_273; // op=pyc.comb
wire [15:0] pyc_comb_281; // op=pyc.comb
wire [3:0] pyc_comb_285; // op=pyc.comb
wire [15:0] pyc_comb_289; // op=pyc.comb
wire [7:0] pyc_comb_292; // op=pyc.comb
wire [127:0] pyc_comb_312; // op=pyc.comb
wire [96:0] pyc_comb_319; // op=pyc.comb
wire [29:0] pyc_comb_320; // op=pyc.comb
wire [29:0] pyc_comb_323; // op=pyc.comb
wire [614:0] pyc_comb_324; // op=pyc.comb
wire [96:0] pyc_comb_331; // op=pyc.comb
wire [29:0] pyc_comb_332; // op=pyc.comb
wire [614:0] pyc_comb_333; // op=pyc.comb
wire [1:0] pyc_comb_334; // op=pyc.comb
wire [614:0] pyc_comb_57; // op=pyc.comb
wire [29:0] pyc_comb_58; // op=pyc.comb
wire [7:0] pyc_comb_59; // op=pyc.comb
wire [15:0] pyc_comb_60; // op=pyc.comb
wire [3:0] pyc_comb_61; // op=pyc.comb
wire [63:0] pyc_comb_62; // op=pyc.comb
wire [63:0] pyc_comb_63; // op=pyc.comb
wire [63:0] pyc_comb_64; // op=pyc.comb
wire [63:0] pyc_comb_65; // op=pyc.comb
wire [63:0] pyc_comb_66; // op=pyc.comb
wire [63:0] pyc_comb_67; // op=pyc.comb
wire [63:0] pyc_comb_68; // op=pyc.comb
wire [63:0] pyc_comb_69; // op=pyc.comb
wire [3:0] pyc_comb_70; // op=pyc.comb
wire [7:0] pyc_comb_71; // op=pyc.comb
wire [3:0] pyc_comb_72; // op=pyc.comb
wire [15:0] pyc_comb_73; // op=pyc.comb
wire [127:0] pyc_comb_74; // op=pyc.comb
wire [63:0] pyc_comb_75; // op=pyc.comb
wire [1:0] pyc_comb_76; // op=pyc.comb
wire [6:0] pyc_comb_77; // op=pyc.comb
wire [6:0] pyc_comb_78; // op=pyc.comb
wire [6:0] pyc_comb_79; // op=pyc.comb
wire [6:0] pyc_comb_80; // op=pyc.comb
wire [6:0] pyc_comb_81; // op=pyc.comb
wire [6:0] pyc_comb_82; // op=pyc.comb
wire [6:0] pyc_comb_83; // op=pyc.comb
wire [6:0] pyc_comb_84; // op=pyc.comb
wire [6:0] pyc_comb_85; // op=pyc.comb
wire [6:0] pyc_comb_86; // op=pyc.comb
wire [6:0] pyc_comb_87; // op=pyc.comb
wire [6:0] pyc_comb_88; // op=pyc.comb
wire [6:0] pyc_comb_89; // op=pyc.comb
wire [6:0] pyc_comb_90; // op=pyc.comb
wire [6:0] pyc_comb_91; // op=pyc.comb
wire [6:0] pyc_comb_92; // op=pyc.comb
wire [6:0] pyc_comb_93; // op=pyc.comb
wire [6:0] pyc_comb_94; // op=pyc.comb
wire [6:0] pyc_comb_95; // op=pyc.comb
wire [6:0] pyc_comb_96; // op=pyc.comb
wire [6:0] pyc_comb_97; // op=pyc.comb
wire [6:0] pyc_comb_98; // op=pyc.comb
wire [6:0] pyc_comb_99; // op=pyc.comb
wire [127:0] pyc_concat_293; // op=pyc.concat
wire [127:0] pyc_concat_294; // op=pyc.concat
wire [127:0] pyc_concat_295; // op=pyc.concat
wire [127:0] pyc_concat_296; // op=pyc.concat
wire [614:0] pyc_constant_1; // op=pyc.constant
wire [63:0] pyc_constant_10; // op=pyc.constant
wire [63:0] pyc_constant_11; // op=pyc.constant
wire [63:0] pyc_constant_12; // op=pyc.constant
wire [63:0] pyc_constant_13; // op=pyc.constant
wire [3:0] pyc_constant_14; // op=pyc.constant
wire [7:0] pyc_constant_15; // op=pyc.constant
wire [3:0] pyc_constant_16; // op=pyc.constant
wire [15:0] pyc_constant_17; // op=pyc.constant
wire [127:0] pyc_constant_18; // op=pyc.constant
wire [63:0] pyc_constant_19; // op=pyc.constant
wire [29:0] pyc_constant_2; // op=pyc.constant
wire [1:0] pyc_constant_20; // op=pyc.constant
wire [6:0] pyc_constant_21; // op=pyc.constant
wire [6:0] pyc_constant_22; // op=pyc.constant
wire [6:0] pyc_constant_23; // op=pyc.constant
wire [6:0] pyc_constant_24; // op=pyc.constant
wire [6:0] pyc_constant_25; // op=pyc.constant
wire [6:0] pyc_constant_26; // op=pyc.constant
wire [6:0] pyc_constant_27; // op=pyc.constant
wire [6:0] pyc_constant_28; // op=pyc.constant
wire [6:0] pyc_constant_29; // op=pyc.constant
wire [7:0] pyc_constant_3; // op=pyc.constant
wire [6:0] pyc_constant_30; // op=pyc.constant
wire [6:0] pyc_constant_31; // op=pyc.constant
wire [6:0] pyc_constant_32; // op=pyc.constant
wire [6:0] pyc_constant_33; // op=pyc.constant
wire [6:0] pyc_constant_34; // op=pyc.constant
wire [6:0] pyc_constant_35; // op=pyc.constant
wire [6:0] pyc_constant_36; // op=pyc.constant
wire [6:0] pyc_constant_37; // op=pyc.constant
wire [6:0] pyc_constant_38; // op=pyc.constant
wire [6:0] pyc_constant_39; // op=pyc.constant
wire [15:0] pyc_constant_4; // op=pyc.constant
wire [6:0] pyc_constant_40; // op=pyc.constant
wire [6:0] pyc_constant_41; // op=pyc.constant
wire [6:0] pyc_constant_42; // op=pyc.constant
wire [6:0] pyc_constant_43; // op=pyc.constant
wire [6:0] pyc_constant_44; // op=pyc.constant
wire [6:0] pyc_constant_45; // op=pyc.constant
wire pyc_constant_46; // op=pyc.constant
wire pyc_constant_47; // op=pyc.constant
wire [2:0] pyc_constant_48; // op=pyc.constant
wire [17:0] pyc_constant_49; // op=pyc.constant
wire [3:0] pyc_constant_5; // op=pyc.constant
wire [1:0] pyc_constant_50; // op=pyc.constant
wire [96:0] pyc_constant_51; // op=pyc.constant
wire [31:0] pyc_constant_52; // op=pyc.constant
wire [63:0] pyc_constant_6; // op=pyc.constant
wire [63:0] pyc_constant_7; // op=pyc.constant
wire [63:0] pyc_constant_8; // op=pyc.constant
wire [63:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_123; // op=pyc.eq
wire pyc_eq_124; // op=pyc.eq
wire pyc_eq_125; // op=pyc.eq
wire pyc_eq_126; // op=pyc.eq
wire pyc_eq_127; // op=pyc.eq
wire pyc_eq_128; // op=pyc.eq
wire pyc_eq_129; // op=pyc.eq
wire pyc_eq_130; // op=pyc.eq
wire pyc_eq_131; // op=pyc.eq
wire pyc_eq_132; // op=pyc.eq
wire pyc_eq_133; // op=pyc.eq
wire pyc_eq_134; // op=pyc.eq
wire pyc_eq_135; // op=pyc.eq
wire pyc_eq_136; // op=pyc.eq
wire pyc_eq_137; // op=pyc.eq
wire pyc_eq_138; // op=pyc.eq
wire pyc_eq_139; // op=pyc.eq
wire pyc_eq_140; // op=pyc.eq
wire pyc_eq_141; // op=pyc.eq
wire pyc_eq_142; // op=pyc.eq
wire pyc_eq_143; // op=pyc.eq
wire pyc_eq_144; // op=pyc.eq
wire pyc_eq_145; // op=pyc.eq
wire pyc_eq_146; // op=pyc.eq
wire pyc_eq_147; // op=pyc.eq
wire [6:0] pyc_extract_122; // op=pyc.extract
wire [31:0] pyc_extract_206; // op=pyc.extract
wire [39:0] pyc_extract_209; // op=pyc.extract
wire [31:0] pyc_extract_219; // op=pyc.extract
wire [3:0] pyc_extract_224; // op=pyc.extract
wire [3:0] pyc_extract_225; // op=pyc.extract
wire pyc_extract_274; // op=pyc.extract
wire pyc_extract_275; // op=pyc.extract
wire [25:0] pyc_extract_314; // op=pyc.extract
wire [31:0] pyc_extract_55; // op=pyc.extract
wire [31:0] pyc_extract_56; // op=pyc.extract
wire [31:0] pyc_mux_115; // op=pyc.mux
wire [96:0] pyc_mux_119; // op=pyc.mux
wire [96:0] pyc_mux_120; // op=pyc.mux
wire [96:0] pyc_mux_172; // op=pyc.mux
wire [96:0] pyc_mux_173; // op=pyc.mux
wire [1:0] pyc_mux_180; // op=pyc.mux
wire [1:0] pyc_mux_181; // op=pyc.mux
wire [17:0] pyc_mux_186; // op=pyc.mux
wire [1:0] pyc_mux_187; // op=pyc.mux
wire [2:0] pyc_mux_188; // op=pyc.mux
wire [31:0] pyc_mux_189; // op=pyc.mux
wire [63:0] pyc_mux_236; // op=pyc.mux
wire [63:0] pyc_mux_242; // op=pyc.mux
wire [63:0] pyc_mux_247; // op=pyc.mux
wire [63:0] pyc_mux_252; // op=pyc.mux
wire [63:0] pyc_mux_257; // op=pyc.mux
wire [63:0] pyc_mux_262; // op=pyc.mux
wire [63:0] pyc_mux_267; // op=pyc.mux
wire [63:0] pyc_mux_272; // op=pyc.mux
wire [15:0] pyc_mux_280; // op=pyc.mux
wire [3:0] pyc_mux_283; // op=pyc.mux
wire [3:0] pyc_mux_284; // op=pyc.mux
wire [15:0] pyc_mux_287; // op=pyc.mux
wire [15:0] pyc_mux_288; // op=pyc.mux
wire [7:0] pyc_mux_291; // op=pyc.mux
wire [127:0] pyc_mux_311; // op=pyc.mux
wire [96:0] pyc_mux_327; // op=pyc.mux
wire [29:0] pyc_mux_328; // op=pyc.mux
wire [614:0] pyc_mux_329; // op=pyc.mux
wire [1:0] pyc_mux_330; // op=pyc.mux
wire pyc_not_54; // op=pyc.not
wire pyc_or_148; // op=pyc.or
wire pyc_or_149; // op=pyc.or
wire pyc_or_150; // op=pyc.or
wire pyc_or_151; // op=pyc.or
wire pyc_or_152; // op=pyc.or
wire pyc_or_153; // op=pyc.or
wire pyc_or_154; // op=pyc.or
wire pyc_or_155; // op=pyc.or
wire pyc_or_156; // op=pyc.or
wire pyc_or_157; // op=pyc.or
wire pyc_or_158; // op=pyc.or
wire pyc_or_159; // op=pyc.or
wire pyc_or_160; // op=pyc.or
wire pyc_or_161; // op=pyc.or
wire pyc_or_162; // op=pyc.or
wire pyc_or_163; // op=pyc.or
wire pyc_or_164; // op=pyc.or
wire pyc_or_165; // op=pyc.or
wire pyc_or_166; // op=pyc.or
wire pyc_or_167; // op=pyc.or
wire pyc_or_168; // op=pyc.or
wire pyc_or_169; // op=pyc.or
wire pyc_or_170; // op=pyc.or
wire pyc_or_171; // op=pyc.or
wire [15:0] pyc_or_279; // op=pyc.or
wire [29:0] pyc_or_318; // op=pyc.or
wire [96:0] pyc_reg_116; // op=pyc.reg
wire pyc_reg_117; // op=pyc.reg
wire [96:0] pyc_reg_118; // op=pyc.reg
wire [1:0] pyc_reg_176; // op=pyc.reg
wire [63:0] pyc_reg_190; // op=pyc.reg
wire [63:0] pyc_reg_191; // op=pyc.reg
wire [63:0] pyc_reg_192; // op=pyc.reg
wire [63:0] pyc_reg_193; // op=pyc.reg
wire [63:0] pyc_reg_194; // op=pyc.reg
wire [63:0] pyc_reg_195; // op=pyc.reg
wire [63:0] pyc_reg_196; // op=pyc.reg
wire [63:0] pyc_reg_197; // op=pyc.reg
wire [127:0] pyc_reg_198; // op=pyc.reg
wire [15:0] pyc_reg_199; // op=pyc.reg
wire [3:0] pyc_reg_200; // op=pyc.reg
wire [15:0] pyc_reg_201; // op=pyc.reg
wire [7:0] pyc_reg_202; // op=pyc.reg
wire [96:0] pyc_reg_313; // op=pyc.reg
wire [29:0] pyc_reg_321; // op=pyc.reg
wire [614:0] pyc_reg_325; // op=pyc.reg
wire [1:0] pyc_reg_326; // op=pyc.reg
wire pyc_reset_active_53; // op=pyc.reset_active
wire [15:0] pyc_shli_277; // op=pyc.shli
wire [29:0] pyc_shli_316; // op=pyc.shli
wire [31:0] pyc_sync_mem_231; // op=pyc.sync_mem
wire [63:0] pyc_xor_205; // op=pyc.xor
wire [63:0] pyc_xor_208; // op=pyc.xor
wire [63:0] pyc_xor_211; // op=pyc.xor
wire [63:0] pyc_xor_213; // op=pyc.xor
wire [63:0] pyc_xor_215; // op=pyc.xor
wire [63:0] pyc_xor_217; // op=pyc.xor
wire [63:0] pyc_xor_218; // op=pyc.xor
wire [63:0] pyc_xor_221; // op=pyc.xor
wire [63:0] pyc_xor_223; // op=pyc.xor
wire [63:0] pyc_xor_233; // op=pyc.xor
wire [63:0] pyc_xor_234; // op=pyc.xor
wire [63:0] pyc_xor_235; // op=pyc.xor
wire [63:0] pyc_xor_239; // op=pyc.xor
wire [63:0] pyc_xor_240; // op=pyc.xor
wire [63:0] pyc_xor_241; // op=pyc.xor
wire [63:0] pyc_xor_244; // op=pyc.xor
wire [63:0] pyc_xor_245; // op=pyc.xor
wire [63:0] pyc_xor_246; // op=pyc.xor
wire [63:0] pyc_xor_249; // op=pyc.xor
wire [63:0] pyc_xor_250; // op=pyc.xor
wire [63:0] pyc_xor_251; // op=pyc.xor
wire [63:0] pyc_xor_254; // op=pyc.xor
wire [63:0] pyc_xor_255; // op=pyc.xor
wire [63:0] pyc_xor_256; // op=pyc.xor
wire [63:0] pyc_xor_259; // op=pyc.xor
wire [63:0] pyc_xor_260; // op=pyc.xor
wire [63:0] pyc_xor_261; // op=pyc.xor
wire [63:0] pyc_xor_264; // op=pyc.xor
wire [63:0] pyc_xor_265; // op=pyc.xor
wire [63:0] pyc_xor_266; // op=pyc.xor
wire [63:0] pyc_xor_269; // op=pyc.xor
wire [63:0] pyc_xor_270; // op=pyc.xor
wire [63:0] pyc_xor_271; // op=pyc.xor
wire pyc_xor_276; // op=pyc.xor
wire [127:0] pyc_xor_297; // op=pyc.xor
wire [127:0] pyc_xor_298; // op=pyc.xor
wire [127:0] pyc_xor_299; // op=pyc.xor
wire [127:0] pyc_xor_301; // op=pyc.xor
wire [127:0] pyc_xor_303; // op=pyc.xor
wire [127:0] pyc_xor_305; // op=pyc.xor
wire [127:0] pyc_xor_307; // op=pyc.xor
wire [127:0] pyc_xor_309; // op=pyc.xor
wire [127:0] pyc_xor_310; // op=pyc.xor
wire [63:0] pyc_zext_203; // op=pyc.zext
wire [63:0] pyc_zext_204; // op=pyc.zext
wire [63:0] pyc_zext_207; // op=pyc.zext
wire [63:0] pyc_zext_210; // op=pyc.zext
wire [63:0] pyc_zext_212; // op=pyc.zext
wire [63:0] pyc_zext_214; // op=pyc.zext
wire [63:0] pyc_zext_216; // op=pyc.zext
wire [63:0] pyc_zext_220; // op=pyc.zext
wire [63:0] pyc_zext_222; // op=pyc.zext
wire [63:0] pyc_zext_232; // op=pyc.zext
wire [15:0] pyc_zext_278; // op=pyc.zext
wire [127:0] pyc_zext_300; // op=pyc.zext
wire [127:0] pyc_zext_302; // op=pyc.zext
wire [127:0] pyc_zext_304; // op=pyc.zext
wire [127:0] pyc_zext_306; // op=pyc.zext
wire [127:0] pyc_zext_308; // op=pyc.zext
wire [29:0] pyc_zext_315; // op=pyc.zext
wire [29:0] pyc_zext_317; // op=pyc.zext
wire [614:0] pyc_zext_322; // op=pyc.zext
wire [1:0] side_rxerr_hold__next; // pyc.name="side_rxerr_hold__next"
wire [2:0] side_rxfill_hold__next; // pyc.name="side_rxfill_hold__next"
wire [17:0] side_rxwkup_hold__next; // pyc.name="side_rxwkup_hold__next"
wire [31:0] snoop_digest_stub__next; // pyc.name="snoop_digest_stub__next"
wire [614:0] txdat_q; // pyc.name="txdat_q"
wire [614:0] txdat_q__next; // pyc.name="txdat_q__next"
wire [31:0] txn_tracker_stub__next; // pyc.name="txn_tracker_stub__next"
wire [1:0] txreq_pend_q; // pyc.name="txreq_pend_q"
wire [1:0] txreq_pend_q__next; // pyc.name="txreq_pend_q__next"
wire [1:0] txreq_pend_stub; // pyc.name="txreq_pend_stub"
wire [1:0] txreq_pend_stub__next; // pyc.name="txreq_pend_stub__next"
wire [96:0] txreq_q; // pyc.name="txreq_q"
wire [96:0] txreq_q__next; // pyc.name="txreq_q__next"
wire [29:0] txrsp_q; // pyc.name="txrsp_q"
wire [29:0] txrsp_q__next; // pyc.name="txrsp_q__next"

// --- Combinational (netlist)
assign _v5_bal_1 = pyc_reg_117;
assign f042_brq_stub = pyc_reg_200;
assign f047_pmu_stub = pyc_reg_201;
assign f060_lfsr_stub = pyc_reg_199;
assign feat_shaft_stub = pyc_reg_198;
assign latched_txreq = pyc_reg_116;
assign mega_feature_0 = pyc_reg_190;
assign mega_feature_1 = pyc_reg_191;
assign mega_feature_2 = pyc_reg_192;
assign mega_feature_3 = pyc_reg_193;
assign mega_feature_4 = pyc_reg_194;
assign mega_feature_5 = pyc_reg_195;
assign mega_feature_6 = pyc_reg_196;
assign mega_feature_7 = pyc_reg_197;
assign txreq_q = pyc_reg_313;
assign pyc_extract_314 = rxrsp[25:0];
assign pyc_zext_315 = {{26{1'b0}}, rsp1_side};
assign pyc_shli_316 = (pyc_zext_315 << 26);
assign pyc_zext_317 = {{4{1'b0}}, pyc_extract_314};
assign pyc_or_318 = (pyc_shli_316 | pyc_zext_317);
assign txrsp_q__next = pyc_or_318;
assign pyc_comb_319 = txreq_q;
assign pyc_comb_320 = txrsp_q__next;
assign txrsp_q = pyc_reg_321;
assign pyc_zext_322 = {{31{1'b0}}, rxdat};
assign txdat_q__next = pyc_zext_322;
assign pyc_comb_323 = txrsp_q;
assign pyc_comb_324 = txdat_q__next;
assign pyc_constant_1 = 615'd0;
assign pyc_constant_2 = 30'd0;
assign pyc_constant_3 = 8'd1;
assign pyc_constant_4 = 16'd1;
assign pyc_constant_5 = 4'd1;
assign pyc_constant_6 = 64'd12473595201;
assign pyc_constant_7 = 64'd6099971477;
assign pyc_constant_8 = 64'd34026840317;
assign pyc_constant_9 = 64'd1839438625;
assign pyc_constant_10 = 64'd3839154729;
assign pyc_constant_11 = 64'd1744638197;
assign pyc_constant_12 = 64'd8099417501;
assign pyc_constant_13 = 64'd2654435769;
assign pyc_constant_14 = 4'd15;
assign pyc_constant_15 = 8'd0;
assign pyc_constant_16 = 4'd0;
assign pyc_constant_17 = 16'd0;
assign pyc_constant_18 = 128'd0;
assign pyc_constant_19 = 64'd0;
assign pyc_constant_20 = 2'd1;
assign pyc_constant_21 = 7'd92;
assign pyc_constant_22 = 7'd89;
assign pyc_constant_23 = 7'd78;
assign pyc_constant_24 = 7'd68;
assign pyc_constant_25 = 7'd67;
assign pyc_constant_26 = 7'd66;
assign pyc_constant_27 = 7'd65;
assign pyc_constant_28 = 7'd39;
assign pyc_constant_29 = 7'd38;
assign pyc_constant_30 = 7'd29;
assign pyc_constant_31 = 7'd28;
assign pyc_constant_32 = 7'd27;
assign pyc_constant_33 = 7'd25;
assign pyc_constant_34 = 7'd23;
assign pyc_constant_35 = 7'd21;
assign pyc_constant_36 = 7'd20;
assign pyc_constant_37 = 7'd13;
assign pyc_constant_38 = 7'd12;
assign pyc_constant_39 = 7'd9;
assign pyc_constant_40 = 7'd8;
assign pyc_constant_41 = 7'd7;
assign pyc_constant_42 = 7'd4;
assign pyc_constant_43 = 7'd3;
assign pyc_constant_44 = 7'd2;
assign pyc_constant_45 = 7'd0;
assign pyc_constant_46 = 1'd0;
assign pyc_constant_47 = 1'd1;
assign pyc_constant_48 = 3'd0;
assign pyc_constant_49 = 18'd0;
assign pyc_constant_50 = 2'd0;
assign pyc_constant_51 = 97'd0;
assign pyc_constant_52 = 32'd0;
assign _v5_bal_2__next = tb_txreq_seed;
assign _v5_bal_1__next = tb_issue_req;
assign pyc_reset_active_53 = rst;
assign pyc_not_54 = (~pyc_reset_active_53);
assign pyc_extract_55 = rxrsp[31:0];
assign pyc_extract_56 = rxsnp[31:0];
assign pyc_comb_57 = pyc_constant_1;
assign pyc_comb_58 = pyc_constant_2;
assign pyc_comb_59 = pyc_constant_3;
assign pyc_comb_60 = pyc_constant_4;
assign pyc_comb_61 = pyc_constant_5;
assign pyc_comb_62 = pyc_constant_6;
assign pyc_comb_63 = pyc_constant_7;
assign pyc_comb_64 = pyc_constant_8;
assign pyc_comb_65 = pyc_constant_9;
assign pyc_comb_66 = pyc_constant_10;
assign pyc_comb_67 = pyc_constant_11;
assign pyc_comb_68 = pyc_constant_12;
assign pyc_comb_69 = pyc_constant_13;
assign pyc_comb_70 = pyc_constant_14;
assign pyc_comb_71 = pyc_constant_15;
assign pyc_comb_72 = pyc_constant_16;
assign pyc_comb_73 = pyc_constant_17;
assign pyc_comb_74 = pyc_constant_18;
assign pyc_comb_75 = pyc_constant_19;
assign pyc_comb_76 = pyc_constant_20;
assign pyc_comb_77 = pyc_constant_21;
assign pyc_comb_78 = pyc_constant_22;
assign pyc_comb_79 = pyc_constant_23;
assign pyc_comb_80 = pyc_constant_24;
assign pyc_comb_81 = pyc_constant_25;
assign pyc_comb_82 = pyc_constant_26;
assign pyc_comb_83 = pyc_constant_27;
assign pyc_comb_84 = pyc_constant_28;
assign pyc_comb_85 = pyc_constant_29;
assign pyc_comb_86 = pyc_constant_30;
assign pyc_comb_87 = pyc_constant_31;
assign pyc_comb_88 = pyc_constant_32;
assign pyc_comb_89 = pyc_constant_33;
assign pyc_comb_90 = pyc_constant_34;
assign pyc_comb_91 = pyc_constant_35;
assign pyc_comb_92 = pyc_constant_36;
assign pyc_comb_93 = pyc_constant_37;
assign pyc_comb_94 = pyc_constant_38;
assign pyc_comb_95 = pyc_constant_39;
assign pyc_comb_96 = pyc_constant_40;
assign pyc_comb_97 = pyc_constant_41;
assign pyc_comb_98 = pyc_constant_42;
assign pyc_comb_99 = pyc_constant_43;
assign pyc_comb_100 = pyc_constant_44;
assign pyc_comb_101 = pyc_constant_45;
assign pyc_comb_102 = pyc_constant_46;
assign pyc_comb_103 = pyc_constant_47;
assign pyc_comb_104 = pyc_constant_48;
assign pyc_comb_105 = pyc_constant_49;
assign pyc_comb_106 = pyc_constant_50;
assign pyc_comb_107 = pyc_constant_51;
assign pyc_comb_108 = pyc_constant_52;
assign pyc_comb_109 = _v5_bal_2__next;
assign pyc_comb_110 = _v5_bal_1__next;
assign pyc_comb_111 = pyc_reset_active_53;
assign pyc_comb_112 = pyc_not_54;
assign pyc_comb_113 = pyc_extract_55;
assign pyc_comb_114 = pyc_extract_56;
assign _v5_bal_2 = pyc_reg_118;
assign pyc_mux_119 = (_v5_bal_1 ? _v5_bal_2 : latched_txreq);
assign pyc_mux_120 = (pyc_comb_111 ? pyc_comb_107 : pyc_mux_119);
assign pyc_comb_121 = pyc_mux_120;
assign latched_txreq__next = pyc_comb_121;
assign pyc_extract_122 = latched_txreq[27:21];
assign pyc_eq_123 = (pyc_extract_122 == pyc_comb_101);
assign pyc_eq_124 = (pyc_extract_122 == pyc_comb_100);
assign pyc_eq_125 = (pyc_extract_122 == pyc_comb_99);
assign pyc_eq_126 = (pyc_extract_122 == pyc_comb_98);
assign pyc_eq_127 = (pyc_extract_122 == pyc_comb_97);
assign pyc_eq_128 = (pyc_extract_122 == pyc_comb_96);
assign pyc_eq_129 = (pyc_extract_122 == pyc_comb_95);
assign pyc_eq_130 = (pyc_extract_122 == pyc_comb_94);
assign pyc_eq_131 = (pyc_extract_122 == pyc_comb_93);
assign pyc_eq_132 = (pyc_extract_122 == pyc_comb_92);
assign pyc_eq_133 = (pyc_extract_122 == pyc_comb_91);
assign pyc_eq_134 = (pyc_extract_122 == pyc_comb_90);
assign pyc_eq_135 = (pyc_extract_122 == pyc_comb_89);
assign pyc_eq_136 = (pyc_extract_122 == pyc_comb_88);
assign pyc_eq_137 = (pyc_extract_122 == pyc_comb_87);
assign pyc_eq_138 = (pyc_extract_122 == pyc_comb_86);
assign pyc_eq_139 = (pyc_extract_122 == pyc_comb_85);
assign pyc_eq_140 = (pyc_extract_122 == pyc_comb_84);
assign pyc_eq_141 = (pyc_extract_122 == pyc_comb_83);
assign pyc_eq_142 = (pyc_extract_122 == pyc_comb_82);
assign pyc_eq_143 = (pyc_extract_122 == pyc_comb_81);
assign pyc_eq_144 = (pyc_extract_122 == pyc_comb_80);
assign pyc_eq_145 = (pyc_extract_122 == pyc_comb_79);
assign pyc_eq_146 = (pyc_extract_122 == pyc_comb_78);
assign pyc_eq_147 = (pyc_extract_122 == pyc_comb_77);
assign pyc_or_148 = (pyc_eq_123 | pyc_eq_124);
assign pyc_or_149 = (pyc_or_148 | pyc_eq_125);
assign pyc_or_150 = (pyc_or_149 | pyc_eq_126);
assign pyc_or_151 = (pyc_or_150 | pyc_eq_127);
assign pyc_or_152 = (pyc_or_151 | pyc_eq_128);
assign pyc_or_153 = (pyc_or_152 | pyc_eq_129);
assign pyc_or_154 = (pyc_or_153 | pyc_eq_130);
assign pyc_or_155 = (pyc_or_154 | pyc_eq_131);
assign pyc_or_156 = (pyc_or_155 | pyc_eq_132);
assign pyc_or_157 = (pyc_or_156 | pyc_eq_133);
assign pyc_or_158 = (pyc_or_157 | pyc_eq_134);
assign pyc_or_159 = (pyc_or_158 | pyc_eq_135);
assign pyc_or_160 = (pyc_or_159 | pyc_eq_136);
assign pyc_or_161 = (pyc_or_160 | pyc_eq_137);
assign pyc_or_162 = (pyc_or_161 | pyc_eq_138);
assign pyc_or_163 = (pyc_or_162 | pyc_eq_139);
assign pyc_or_164 = (pyc_or_163 | pyc_eq_140);
assign pyc_or_165 = (pyc_or_164 | pyc_eq_141);
assign pyc_or_166 = (pyc_or_165 | pyc_eq_142);
assign pyc_or_167 = (pyc_or_166 | pyc_eq_143);
assign pyc_or_168 = (pyc_or_167 | pyc_eq_144);
assign pyc_or_169 = (pyc_or_168 | pyc_eq_145);
assign pyc_or_170 = (pyc_or_169 | pyc_eq_146);
assign pyc_or_171 = (pyc_or_170 | pyc_eq_147);
assign pyc_mux_172 = (pyc_or_171 ? latched_txreq : pyc_comb_107);
assign pyc_mux_173 = (pyc_comb_111 ? pyc_comb_107 : pyc_mux_172);
assign txreq_q__next = pyc_mux_173;
assign pyc_comb_174 = pyc_or_171;
assign pyc_comb_175 = txreq_q__next;
assign txreq_pend_stub = pyc_reg_176;
assign txreq_pend_q__next = txreq_pend_stub;
assign pyc_and_177 = (tb_issue_req & pyc_comb_174);
assign pyc_and_178 = (pyc_and_177 & pyc_comb_112);
assign pyc_add_179 = (txreq_pend_stub + pyc_comb_76);
assign pyc_mux_180 = (pyc_and_178 ? pyc_add_179 : txreq_pend_stub);
assign pyc_mux_181 = (pyc_comb_111 ? pyc_comb_106 : pyc_mux_180);
assign pyc_comb_182 = txreq_pend_stub;
assign pyc_comb_183 = txreq_pend_q__next;
assign pyc_comb_184 = pyc_and_178;
assign pyc_comb_185 = pyc_mux_181;
assign f061_rrip_stub = pyc_reg_202;
assign pyc_zext_203 = {{32{1'b0}}, pyc_comb_113};
assign pyc_zext_204 = {{32{1'b0}}, pyc_comb_114};
assign pyc_xor_205 = (pyc_zext_203 ^ pyc_zext_204);
assign pyc_extract_206 = rxdat[31:0];
assign pyc_zext_207 = {{32{1'b0}}, pyc_extract_206};
assign pyc_xor_208 = (pyc_xor_205 ^ pyc_zext_207);
assign pyc_extract_209 = rxrsp[39:0];
assign pyc_zext_210 = {{24{1'b0}}, pyc_extract_209};
assign pyc_xor_211 = (pyc_xor_208 ^ pyc_zext_210);
assign pyc_zext_212 = {{46{1'b0}}, rxwkup};
assign pyc_xor_213 = (pyc_xor_211 ^ pyc_zext_212);
assign pyc_zext_214 = {{62{1'b0}}, rxerr};
assign pyc_xor_215 = (pyc_xor_213 ^ pyc_zext_214);
assign pyc_zext_216 = {{61{1'b0}}, rxfill};
assign pyc_xor_217 = (pyc_xor_215 ^ pyc_zext_216);
assign pyc_xor_218 = (pyc_xor_217 ^ cfg_word);
assign pyc_extract_219 = latched_txreq[31:0];
assign pyc_zext_220 = {{32{1'b0}}, pyc_extract_219};
assign pyc_xor_221 = (pyc_xor_218 ^ pyc_zext_220);
assign pyc_zext_222 = {{62{1'b0}}, pyc_comb_182};
assign pyc_xor_223 = (pyc_xor_221 ^ pyc_zext_222);
assign pyc_extract_224 = rxdat[3:0];
assign pyc_extract_225 = latched_txreq[34:31];
assign pyc_comb_226 = f061_rrip_stub;
assign pyc_comb_227 = pyc_extract_206;
assign pyc_comb_228 = pyc_xor_223;
assign pyc_comb_229 = pyc_extract_224;
assign pyc_comb_230 = pyc_extract_225;
assign pyc_zext_232 = {{32{1'b0}}, pyc_sync_mem_231};
assign pyc_xor_233 = (pyc_comb_228 ^ pyc_comb_69);
assign pyc_xor_234 = (pyc_xor_233 ^ pyc_zext_232);
assign pyc_xor_235 = (mega_feature_0 ^ pyc_xor_234);
assign pyc_mux_236 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_235);
assign pyc_comb_237 = pyc_zext_232;
assign pyc_comb_238 = pyc_mux_236;
assign mega_feature_0__next = pyc_comb_238;
assign pyc_xor_239 = (pyc_comb_228 ^ pyc_comb_68);
assign pyc_xor_240 = (pyc_xor_239 ^ pyc_comb_237);
assign pyc_xor_241 = (mega_feature_1 ^ pyc_xor_240);
assign pyc_mux_242 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_241);
assign pyc_comb_243 = pyc_mux_242;
assign mega_feature_1__next = pyc_comb_243;
assign pyc_xor_244 = (pyc_comb_228 ^ pyc_comb_67);
assign pyc_xor_245 = (pyc_xor_244 ^ pyc_comb_237);
assign pyc_xor_246 = (mega_feature_2 ^ pyc_xor_245);
assign pyc_mux_247 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_246);
assign pyc_comb_248 = pyc_mux_247;
assign mega_feature_2__next = pyc_comb_248;
assign pyc_xor_249 = (pyc_comb_228 ^ pyc_comb_66);
assign pyc_xor_250 = (pyc_xor_249 ^ pyc_comb_237);
assign pyc_xor_251 = (mega_feature_3 ^ pyc_xor_250);
assign pyc_mux_252 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_251);
assign pyc_comb_253 = pyc_mux_252;
assign mega_feature_3__next = pyc_comb_253;
assign pyc_xor_254 = (pyc_comb_228 ^ pyc_comb_65);
assign pyc_xor_255 = (pyc_xor_254 ^ pyc_comb_237);
assign pyc_xor_256 = (mega_feature_4 ^ pyc_xor_255);
assign pyc_mux_257 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_256);
assign pyc_comb_258 = pyc_mux_257;
assign mega_feature_4__next = pyc_comb_258;
assign pyc_xor_259 = (pyc_comb_228 ^ pyc_comb_64);
assign pyc_xor_260 = (pyc_xor_259 ^ pyc_comb_237);
assign pyc_xor_261 = (mega_feature_5 ^ pyc_xor_260);
assign pyc_mux_262 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_261);
assign pyc_comb_263 = pyc_mux_262;
assign mega_feature_5__next = pyc_comb_263;
assign pyc_xor_264 = (pyc_comb_228 ^ pyc_comb_63);
assign pyc_xor_265 = (pyc_xor_264 ^ pyc_comb_237);
assign pyc_xor_266 = (mega_feature_6 ^ pyc_xor_265);
assign pyc_mux_267 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_266);
assign pyc_comb_268 = pyc_mux_267;
assign mega_feature_6__next = pyc_comb_268;
assign pyc_xor_269 = (pyc_comb_228 ^ pyc_comb_62);
assign pyc_xor_270 = (pyc_xor_269 ^ pyc_comb_237);
assign pyc_xor_271 = (mega_feature_7 ^ pyc_xor_270);
assign pyc_mux_272 = (pyc_comb_111 ? pyc_comb_75 : pyc_xor_271);
assign pyc_comb_273 = pyc_mux_272;
assign mega_feature_7__next = pyc_comb_273;
assign pyc_extract_274 = f060_lfsr_stub[15];
assign pyc_extract_275 = f060_lfsr_stub[12];
assign pyc_xor_276 = (pyc_extract_274 ^ pyc_extract_275);
assign pyc_shli_277 = (f060_lfsr_stub << 1);
assign pyc_zext_278 = {{15{1'b0}}, pyc_xor_276};
assign pyc_or_279 = (pyc_shli_277 | pyc_zext_278);
assign pyc_mux_280 = (pyc_comb_111 ? pyc_comb_73 : pyc_or_279);
assign pyc_comb_281 = pyc_mux_280;
assign f060_lfsr_stub__next = pyc_comb_281;
assign pyc_add_282 = (f042_brq_stub + pyc_comb_61);
assign pyc_mux_283 = (pyc_comb_184 ? pyc_add_282 : f042_brq_stub);
assign pyc_mux_284 = (pyc_comb_111 ? pyc_comb_72 : pyc_mux_283);
assign pyc_comb_285 = pyc_mux_284;
assign f042_brq_stub__next = pyc_comb_285;
assign pyc_add_286 = (f047_pmu_stub + pyc_comb_60);
assign pyc_mux_287 = (pyc_comb_184 ? pyc_add_286 : f047_pmu_stub);
assign pyc_mux_288 = (pyc_comb_111 ? pyc_comb_73 : pyc_mux_287);
assign pyc_comb_289 = pyc_mux_288;
assign f047_pmu_stub__next = pyc_comb_289;
assign pyc_add_290 = (pyc_comb_226 + pyc_comb_59);
assign pyc_mux_291 = (pyc_comb_111 ? pyc_comb_71 : pyc_add_290);
assign pyc_comb_292 = pyc_mux_291;
assign f061_rrip_stub__next = pyc_comb_292;
assign pyc_concat_293 = {mega_feature_0, mega_feature_1};
assign pyc_concat_294 = {mega_feature_2, mega_feature_3};
assign pyc_concat_295 = {mega_feature_4, mega_feature_5};
assign pyc_concat_296 = {mega_feature_6, mega_feature_7};
assign pyc_xor_297 = (pyc_concat_293 ^ pyc_concat_294);
assign pyc_xor_298 = (pyc_xor_297 ^ pyc_concat_295);
assign pyc_xor_299 = (pyc_xor_298 ^ pyc_concat_296);
assign pyc_zext_300 = {{112{1'b0}}, f060_lfsr_stub};
assign pyc_xor_301 = (pyc_xor_299 ^ pyc_zext_300);
assign pyc_zext_302 = {{124{1'b0}}, f042_brq_stub};
assign pyc_xor_303 = (pyc_xor_301 ^ pyc_zext_302);
assign pyc_zext_304 = {{112{1'b0}}, f047_pmu_stub};
assign pyc_xor_305 = (pyc_xor_303 ^ pyc_zext_304);
assign pyc_zext_306 = {{120{1'b0}}, pyc_comb_226};
assign pyc_xor_307 = (pyc_xor_305 ^ pyc_zext_306);
assign pyc_zext_308 = {{96{1'b0}}, pyc_sync_mem_231};
assign pyc_xor_309 = (pyc_xor_307 ^ pyc_zext_308);
assign pyc_xor_310 = (feat_shaft_stub ^ pyc_xor_309);
assign pyc_mux_311 = (pyc_comb_111 ? pyc_comb_74 : pyc_xor_310);
assign pyc_comb_312 = pyc_mux_311;
assign feat_shaft_stub__next = pyc_comb_312;
assign pyc_mux_115 = (pyc_comb_111 ? pyc_comb_108 : pyc_comb_113);
assign pyc_mux_186 = (pyc_comb_111 ? pyc_comb_105 : rxwkup);
assign pyc_mux_187 = (pyc_comb_111 ? pyc_comb_106 : rxerr);
assign pyc_mux_188 = (pyc_comb_111 ? pyc_comb_104 : rxfill);
assign pyc_mux_189 = (pyc_comb_111 ? pyc_comb_108 : pyc_comb_114);
assign side_rxerr_hold__next = pyc_mux_187;
assign side_rxfill_hold__next = pyc_mux_188;
assign side_rxwkup_hold__next = pyc_mux_186;
assign snoop_digest_stub__next = pyc_mux_189;
assign txdat_q = pyc_reg_325;
assign txreq_pend_q = pyc_reg_326;
assign pyc_mux_327 = (pyc_comb_111 ? pyc_comb_107 : pyc_comb_319);
assign pyc_mux_328 = (pyc_comb_111 ? pyc_comb_58 : pyc_comb_323);
assign pyc_mux_329 = (pyc_comb_111 ? pyc_comb_57 : txdat_q);
assign pyc_mux_330 = (pyc_comb_111 ? pyc_comb_106 : txreq_pend_q);
assign pyc_comb_331 = pyc_mux_327;
assign pyc_comb_332 = pyc_mux_328;
assign pyc_comb_333 = pyc_mux_329;
assign pyc_comb_334 = pyc_mux_330;
assign txn_tracker_stub__next = pyc_mux_115;
assign txreq_pend_stub__next = pyc_comb_185;

// --- Sequential primitives
pyc_sync_mem #(.ADDR_WIDTH(4), .DATA_WIDTH(32), .DEPTH(16)) f035_data_ram_stub (
  .clk(clk),
  .rst(rst),
  .ren(pyc_comb_112),
  .raddr(pyc_comb_229),
  .rdata(pyc_sync_mem_231),
  .wvalid(pyc_comb_184),
  .waddr(pyc_comb_230),
  .wdata(pyc_comb_227),
  .wstrb(pyc_comb_70)
);
pyc_reg #(.WIDTH(97)) pyc_reg_116_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(latched_txreq__next),
  .init(pyc_comb_107),
  .q(pyc_reg_116)
);
pyc_reg #(.WIDTH(1)) pyc_reg_117_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(pyc_comb_110),
  .init(pyc_comb_102),
  .q(pyc_reg_117)
);
pyc_reg #(.WIDTH(97)) pyc_reg_118_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(pyc_comb_109),
  .init(pyc_comb_107),
  .q(pyc_reg_118)
);
pyc_reg #(.WIDTH(2)) pyc_reg_176_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(txreq_pend_stub__next),
  .init(pyc_comb_106),
  .q(pyc_reg_176)
);
pyc_reg #(.WIDTH(64)) pyc_reg_190_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_0__next),
  .init(pyc_comb_75),
  .q(pyc_reg_190)
);
pyc_reg #(.WIDTH(64)) pyc_reg_191_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_1__next),
  .init(pyc_comb_75),
  .q(pyc_reg_191)
);
pyc_reg #(.WIDTH(64)) pyc_reg_192_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_2__next),
  .init(pyc_comb_75),
  .q(pyc_reg_192)
);
pyc_reg #(.WIDTH(64)) pyc_reg_193_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_3__next),
  .init(pyc_comb_75),
  .q(pyc_reg_193)
);
pyc_reg #(.WIDTH(64)) pyc_reg_194_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_4__next),
  .init(pyc_comb_75),
  .q(pyc_reg_194)
);
pyc_reg #(.WIDTH(64)) pyc_reg_195_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_5__next),
  .init(pyc_comb_75),
  .q(pyc_reg_195)
);
pyc_reg #(.WIDTH(64)) pyc_reg_196_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_6__next),
  .init(pyc_comb_75),
  .q(pyc_reg_196)
);
pyc_reg #(.WIDTH(64)) pyc_reg_197_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(mega_feature_7__next),
  .init(pyc_comb_75),
  .q(pyc_reg_197)
);
pyc_reg #(.WIDTH(128)) pyc_reg_198_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(feat_shaft_stub__next),
  .init(pyc_comb_74),
  .q(pyc_reg_198)
);
pyc_reg #(.WIDTH(16)) pyc_reg_199_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(f060_lfsr_stub__next),
  .init(pyc_comb_73),
  .q(pyc_reg_199)
);
pyc_reg #(.WIDTH(4)) pyc_reg_200_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(f042_brq_stub__next),
  .init(pyc_comb_72),
  .q(pyc_reg_200)
);
pyc_reg #(.WIDTH(16)) pyc_reg_201_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(f047_pmu_stub__next),
  .init(pyc_comb_73),
  .q(pyc_reg_201)
);
pyc_reg #(.WIDTH(8)) pyc_reg_202_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(f061_rrip_stub__next),
  .init(pyc_comb_71),
  .q(pyc_reg_202)
);
pyc_reg #(.WIDTH(97)) pyc_reg_313_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(pyc_comb_175),
  .init(pyc_comb_107),
  .q(pyc_reg_313)
);
pyc_reg #(.WIDTH(30)) pyc_reg_321_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(pyc_comb_320),
  .init(pyc_comb_58),
  .q(pyc_reg_321)
);
pyc_reg #(.WIDTH(615)) pyc_reg_325_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(pyc_comb_324),
  .init(pyc_comb_57),
  .q(pyc_reg_325)
);
pyc_reg #(.WIDTH(2)) pyc_reg_326_inst (
  .clk(clk),
  .rst(rst),
  .en(pyc_comb_103),
  .d(pyc_comb_183),
  .init(pyc_comb_106),
  .q(pyc_reg_326)
);

assign txreq = pyc_comb_331;
assign txrsp = pyc_comb_332;
assign txdat = pyc_comb_333;
assign txreq_pend = pyc_comb_334;

endmodule

